name: Renovate Run

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v32.63.1
        with:
          token: ${{ secrets.GH_TOKEN }}
