name: Renovate Embedded Bins

on:
  push:
    branches:
      - main  # Triggers on every push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper version checking
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_CONFIG_FILE: 'renovate/renovate.json'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_BINARY_SOURCE: 'local'
          LOG_FORMAT: 'json'
          RENOVATE_PLATFORM_COMMIT: true
