name: Renovate Test

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Run in dry-run mode'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_CONFIG_FILE: 'renovate/renovate.json'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_BINARY_SOURCE: 'local'
          LOG_FORMAT: 'json'
          RENOVATE_PLATFORM_COMMIT: true
          # Test specific settings
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dryRun }}
          RENOVATE_FORCE: true